##### Supervised Training ######
Train:
  wandb : True    # log with wandb
  wandb_proj_name: '20240215_MaskingDepth_multiframe'
  model_name: 'cvlab05_gpu3_kitti_bs8_ViTpre_multiframe(t,t-1,t-2)_mask(t)ratio(0.6)'  # model names to save log file or wandb.
  wandb_log_path: '/media/dataset1/jinlovespho_log/monodepth/MaskingDepth/wandb/20240215'
  log_path: '/media/dataset1/jinlovespho_log/monodepth/MaskingDepth/log/20240215'  # path to the log file, only works when the wandb option is False.
  use_cuda: True
  seed: 41
  start_epoch: 0
  end_epoch: 50
  batch_size: 8
  num_workers: 8
  lr: 1e-4
  d_consistency : 0.0  # depth consistency loss weight
  f_consistency : 0.0  # feature consistency loss weight
  K: 1                 # set number of K for K-way masking, 64 is the default
  load_optim : False
  
  model: 
    baseline: "DPT_Multiframe_mask_t"    # ["DPT", "monodepth2", "DPT_Multiframe", "DPT_Multiframe_mask_t"]
    masking_ratio: 0.6                   # set masking ratio !
    num_frame_to_mask: 1                 # set num_frame_to_mask=2 to mask (t, t-1)frame 
    max_depth: 80.0    # use 10 for NYU and 80 for KITTI depth
    load_weight : False
    weight_path : './weight'
    mlp_head: False    # prediction head for feature consistency loss

  add_model:
    uncert: False      # use uncertainty network. if True, consistency loss is weighted by uncertainty
    load_weight : False
    weight_path : './weight'
    threshold: 0.7

  data:
    height: 192  # data 의 (height,width)=(192,640) 으로 reshape 한 것 
    width: 640
    dataset: 'kitti_depth_multiframe' #'kitti_depth_multiframe'
    num_prev_frame: 2                   # 현재 t_frame 기준으로 이전 두 개 frame: t-2_frame, t-1_frame을 가져오고 싶다는 것
    splits: 'eigen_temp'
    data_path: '/media/data1/KITTI'
    img_ext: '.jpg'
