##### Supervised Training ######
Train:
  wandb : True
  wandb_proj_name: '20240215_MaskingDepth_multiframe'
  model_name: 'gpu0_kitti_depth_original_baseline'  # model names to save log file or wandb.
  log_path: './log/20240215'  # path to the log file, only works when the wandb option is False.
  use_cuda: True
  seed: 41
  start_epoch: 0
  end_epoch: 50
  batch_size: 8
  num_workers: 1
  lr: 1e-4
  d_consistency : 0.0  # depth consistency loss weight
  f_consistency : 0.0  # feature consistency loss weight
  K: 1                 # set number of K for K-way masking, 64 is the default
  load_optim : False
  
  model:
    baseline: "DPT"    # ["DPT", "monodepth2"]
    max_depth: 80.0    # use 10 for NYU and 80 for KITTI depth
    load_weight : False
    weight_path : './weight'
    mlp_head: False    # prediction head for feature consistency loss
  add_model:
    uncert: False      # use uncertainty network. if True, consistency loss is weighted by uncertainty
    load_weight : False
    weight_path : './weight'
    threshold: 0.7

  data:
    height: 192  # data 의 (height,width)=(192,640) 으로 reshape 한 것 
    width: 640
    dataset: 'kitti_depth' #'kitti_depth_multiframe'
    num_prev_frame: 0                   # 현재 t_frame 기준으로 이전 두 개 frame: t-2_frame, t-1_frame을 가져오고 싶다는 것 
    splits: 'eigen_temp'
    data_path: '/home/cvlab08/projects/data/KITTI'
    img_ext: '.jpg'
