##### Supervised Training ######
Train:
  wandb : False  # log with wandb
  wandb_proj_name: '20240215_MaskingDepth_multiframe'
  model_name: 'pho_server5_gpu0123_kitti_bs8_mask00_enc(croco_vit_base)_try5(conv4d64)(my_reshape)'  # model names to save log file or wandb.
  wandb_log_path: '/media/data1/jinlovespho/log/mfdepth'
  log_path: '/media/data1/jinlovespho/log/mfdepth'  # path to the log file, only works when the wandb option is False.
  use_cuda: True
  seed: 41
  start_epoch: 0
  end_epoch: 50
  save_epoch_freq: 3
  batch_size: 8
  num_workers: 8
  lr: 1e-4
  K: 1                 # set number of K for K-way masking, 64 is the default
  load_optim : False
  
  model: 
    baseline: 'try5'               # ['baseline', 'try1', 'try2', , ]
    vit_type: 'vit_base'               # ['vit_base', 'vit_large']        
    masking_ratio: 0.0                 # set masking ratio !
    num_frame_to_mask: 1                 # set num_frame_to_mask=2 to mask (t, t-1)frame 
    cross_attn_depth: 4
    enable_color_loss: False       # True for COLOR LOSS 
    max_depth: 80.0    # use 10 for NYU and 80 for KITTI depth
    load_weight : False
    weight_path : './weight'
    pretrained_weight : 'croco'

  data:
    height: 192  # data 의 (height,width)=(192,640) 으로 reshape 한 것, 원래 이미지 사이즈: (375,1242)
    width: 640 
    dataset: 'kitti_depth_multiframe' #'kitti_depth_multiframe'
    num_prev_frame: 1                   # 현재 t_frame 기준으로 이전 두 개 frame: t-2_frame, t-1_frame을 가져오고 싶다는 것
    splits: 'eigen_temp'
    data_path: '/media/data1/KITTI'
    img_ext: '.jpg'
