##### Supervised Training ######
Train:
  model_name: 'pho'  # model names to save log file or wandb.
  log_path: './log'  # path to the log file, only works when the wandb option is False.
  use_cuda: True
  seed: 41
  start_epoch: 0
  end_epoch: 50
  batch_size: 4
  num_workers: 8
  lr: 1e-4
  d_consistency : 0.0  # depth consistency loss weight
  f_consistency : 0.0  # feature consistency loss weight
  K: 1                 # set number of K for K-way masking, 64 is the default
  wandb : False
  load_optim : False
  
  model:
    baseline: "DPT"    # ["DPT", "monodepth2"]
    max_depth: 80.0    # use 10 for NYU and 80 for KITTI depth
    load_weight : False
    weight_path : './weight'
    mlp_head: False    # prediction head for feature consistency loss
  add_model:
    uncert: False      # use uncertainty network. if True, consistency loss is weighted by uncertainty
    load_weight : False
    weight_path : './weight'
    threshold: 0.7

  data:
    height: 192
    width: 640
    dataset: 'kitti_depth'
    splits: 'eigen_temp'
    data_path: '/mnt/ssd2/dataset/kitti_raw'
    img_ext: '.png'
